### ISSUE TITLE
custom program error: 0x139

### ISSUE THREAD

**Issue by kkwl777** [exiled-apes/candy-machine-mint#122]
**After successful upload and verification that all assets are listed as onChain:true, and uploaded to Arweave running:** 

ts-node candy-machine-cli.ts create_candy_machine assets -k ~/.config/solana/dev1.json --env mainnet-beta -p 0.3

**returns**

wallet public key: mypublickey
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20320 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (C:\Users\kl\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\kl\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\kl\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\kl\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\kl\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20320 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:7456) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (C:\Users\kl\metaplex\js\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (C:\Users\kl\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aosagula** [comment]
I today upload 6300 to the mainnet, try the follow
1) run the upload normally wait to finish could take 6 hs 
2) run the candy creation, if you have the error?
3)edit .cache/<file>-temp, replace true for false for all SAVE IT. DONT TOUCH ANYTHING ELSE
3) run step1 again,
