### ISSUE TITLE
Uploading to airweave failed after 1200 successful ones 

### ISSUE THREAD

**Issue by gw19191** [exiled-apes/candy-machine-mint#136]
Received this after only 1200 files uploaded and it still charged me 18 SOL??? Is this SOL lost or are these images still usable? How do I use them and upload the rest?

\node_modules\rpc-websockets\dist\lib\client.js:392
      this.socket.close(code || 1000, data);
                  ^
TypeError: Cannot read properties of undefined (reading 'close')
    at Client.close (C:\Users\gagew\metaplex\js\node_modules\rpc-websockets\dist\lib\client.js:392:19)
    at Timeout._onTimeout (C:\Users\gagew\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3820:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by facundocajen** [comment]
did you find a solution ? what happened to your sol?¿
