### ISSUE TITLE
Error when running metaplex upload candymachinev2

### ISSUE THREAD

**Issue by Flex35** [exiled-apes/candy-machine-mint#215]
after running metaplex upload (ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets \ -e devnet -k ~/.config/solana/devnet-flexxx.json -cp config.json -c example) I receive an error message I'm new to this space so any help would be appreciated

´Beginning the upload for 11 (img+json) pairs
started at: 1642083770967
config for a candy machine with publickey: zB1rNCX6Kcc4BjxxiKDgpGwp7HP5wDDpNT7rGKJWM6Q has been already initialized
Uploading Size 0 undefined
Writing indices 0-9
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: panicked at 'range end index 3117 out of range for slice of length 1927', nft-candy-machine/program/src/lib.rs:490:18
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 67221 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:328:19
    at async Promise.all (index 0)
    at async uploadV2 (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:308:7)
    at async Command.<anonymous> (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    "Program log: panicked at 'range end index 3117 out of range for slice of length 1927', nft-candy-machine/program/src/lib.rs:490:18",
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 67221 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete'
  ]
}
saving config line 0-9 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:328:19
    at async Promise.all (index 0)
    at async uploadV2 (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:308:7)
    at async Command.<anonymous> (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    "Program log: panicked at 'range end index 3117 out of range for slice of length 1927', nft-candy-machine/program/src/lib.rs:490:18",
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 67221 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete'
  ]
}
Writing indices 10-10
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1773 
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: Custom program error: 0x1773
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 6570 of 200000 compute units
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0x1773
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1773
    at Connection.sendEncodedTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (F:\NFT\Coding\metaplex-master\metaplex-master\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:328:19
    at async Promise.all (index 0)
    at async uploadV2 (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:308:7)
    at async Command.<anonymous> (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    'Program log: Custom program error: 0x1773',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 6570 of 200000 compute units',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0x1773'
  ]
}
saving config line 10-10 failed ProgramError: 6003: Index greater than length!
    at Function.parse (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:35:14)
    at Object.rpc [as addConfigLines] (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:328:19
    at async Promise.all (index 0)
    at async uploadV2 (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\commands\upload.ts:308:7)
    at async Command.<anonymous> (F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  code: 6003,
  msg: 'Index greater than length!'
}
Done. Successful = false.
ended at: 2022-01-13T14:22:51.249Z. time taken: 00:00:00´

**Comment by Flex35** [comment]
solved with:

`ts-node F:\NFT\Coding\metaplex-master\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet-flexxx.json -cp config.json -c expandle F:\NFT\Coding\metaplex-master\metaplex-master\assets
`
