### ISSUE TITLE
Invalid Candy Machine ID  

### ISSUE THREAD

**Issue by ThePanthersClub** [exiled-apes/candy-machine-mint#225]
Hi,
When I use yarn start to view my candy machine in the local host, I am able to connect my wallet but when it loads up, the mint button is greyed out. When I open the developer options in chrome I see an error that says:
There was a problem fetching Candy Machine state
Error: Account does not exist <My Candy Machine ID>
    at AccountClient.fetch (vendors~main.chunk.js:69796:13)
    at async getCandyMachineState (main.chunk.js:1512:17)
    at async main.chunk.js:644:22
I have confirmed that this is the candy machine id present in my cache file. It is also present when I run the show command.
Please can anyone help me with this

**Comment by ThePanthersClub** [comment]
This is a screenshot
![error](https://user-images.githubusercontent.com/92586275/155492241-d62b8202-b27f-4ce4-b4b1-9aced4ea6abe.PNG)
