### ISSUE TITLE
Error when try to upload in candy machine

### ISSUE THREAD

**Issue by nftogetyourich** [exiled-apes/candy-machine-mint#227]
PS C:\Users\user\Desktop\solana\metaplex-master> npx ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
- C:\Users\user\Desktop\solana\metaplex-master\~\metaplex\js\packages\cli\src\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at requireResolveNonCached (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:489:16)
    at phase3 (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:263:27)
    at bootstrap (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:44:30)
    at main (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:32:12)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:519:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
  ]
}

**Comment by nftogetyourich** [comment]
i try this and have the other error:


PS C:\Users\user\Desktop\solana\metaplex-master> ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -k ~/.config/solana/devnet.json ./assets  
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
- C:\Users\user\Desktop\solana\metaplex-master\~\metaplex\js\packages\cli\src\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at requireResolveNonCached (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:489:16)
    at phase3 (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:263:27)
    'C:\\Users\\user\\Desktop\\solana\\metaplex-master\\~\\metaplex\\js\\packages\\cli\\src\\imaginaryUncacheableRequireResolveScript'
  ]
}

**Comment by Hser2bio** [comment]
use sugar instead candy-machine-v2-cli.ts, is obsoleted.
