### ISSUE TITLE
Running the create_candy_machine throws error.

### ISSUE THREAD

**Issue by bhupenchn** [exiled-apes/candy-machine-mint#27]
Running the create_candy_machine throws error.
I am on ubuntu18.04, had created the metaplex cli tool with the following command
`npx pkg . -d --targets node14-linux-x64 --output bin/linux/metaplex`

What am I doing wrong? 

```
$ metaplex create_candy_machine -k ~/.config/solana/devnet.json
(node:24021) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at /snapshot/js/packages/cli/build/cli.js:423:63
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:24021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Originally posted by @bhupenchn in https://github.com/exiled-apes/candy-machine-mint/issues/22#issuecomment-916462023_

**Comment by raghibislam** [comment]
metaplex create_candy_machine --keypair ~/.config/solana/id.json --cache-name .cache/temp

you should add cache/temp (this is created after you run metaplex upload command)

**Comment by mx316** [comment]
@raghibislam When I try to create candy machine or try to use the upload, im getting the: (node:99726) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open <my-path>/.config/solana/id.json'

Any ideas?

**Comment by raghibislam** [comment]
Ya so /.config/solana/id.json is the file name and location where your keypair exists so should put the perfect location for your key pair for the solana wallet

**Comment by raghibislam** [comment]
yours may be /.config/solana/keypair.json
