### ISSUE TITLE
Error when running metaplex upload

### ISSUE THREAD

**Issue by kevinfaveri** [exiled-apes/candy-machine-mint#28]
after running megaplex upload (`metaplex upload ./nfts --env devnet --keypair ~/.config/solana/devnet.json`) I get an error like that (it is only 1 nft, basically a 1.png and 1.json file inside this folder):

```bash
File uploaded: arweurl
setting cache for  1
Writing indices 1-1
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x12f
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 6519 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x12f',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 6519 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f'
  ]
}
saving config line 1-1 failed ProgramError
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:31:20)
    at Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 303,
  msg: 'Index greater than length!'
}
Done. Successful = false. If 'false' - rerun
```

**Comment by raghibislam** [comment]
you should rename them like 0.json and 0.png , 1.json , 1.png it works like that.

**Comment by kevinfaveri** [comment]
that was it, thank you!

**Comment by walter-grace** [comment]
> that was it, thank you!

how do you install metaplex cli? when running metaplex upload i get this error
bash: metaplex: command not found

**Comment by redsky500** [comment]
> 

Please explain in more detail.
I have same issue.
Thanks.
