### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by devJovanni12** [exiled-apes/candy-machine-mint#29]
please add the template env file to github, if possible.
I don't know how to write this field.

Thank you in advance.

**Comment by raghibislam** [comment]
REACT_APP_CANDY_MACHINE_CONFIG="get from config"
REACT_APP_CANDY_MACHINE_ID="after running create_candy_machine"
REACT_APP_CANDY_START_DATE=”get this after running metaplex set_start_date cmd”
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com
REACT_APP_TREASURY_ADDRESS="wallet address for sending sol after minting"

**Comment by devJovanni12** [comment]
please let me know the path of the config file and how to get the machine name there.

**Comment by mchebib** [comment]
Something is off when running `npm start`. I get the following error when localhost app runs: Error: Invalid public key input

Looking further, it seems the `.env` are not being read, because the `new PublicKey` is pointing to one directory above my root (and .env file). 

Thoughts?

**Comment by crypt0miester** [comment]
> Something is off when running `npm start`. I get the following error when localhost app runs: Error: Invalid public key input
> 
> Looking further, it seems the `.env` are not being read, because the `new PublicKey` is pointing to one directory above my root (and .env file).
> 
> ![image](https://user-images.githubusercontent.com/10168384/132933016-4a5dd3a5-1e0c-4ca5-8963-f661d2dbf5b1.png)
> 
> Thoughts?


did you run commands "metaplex upload"? 
the value comes after that:  REACT_APP_CANDY_MACHINE_ID
it should be in .cache/temp

**Comment by studentofcoding** [comment]
> did you run commands "metaplex upload"?

How to run "metaplex upload" @crypt0miester, and the other question is how to install it?
I did run it on my cli (windows) and get **not recognized error** in which i believe have to install it first
```
metaplex: The term 'metaplex' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by studentofcoding** [comment]
> create_candy_machine

How I get these env variable
```
REACT_APP_CANDY_MACHINE_CONFIG="get from config"
REACT_APP_CANDY_MACHINE_ID="after running create_candy_machine"
REACT_APP_CANDY_START_DATE=”get this after running metaplex set_start_date cmd”
```

**Comment by Marxpark** [comment]
> > Something is off when running `npm start`. I get the following error when localhost app runs: Error: Invalid public key input
> > Looking further, it seems the `.env` are not being read, because the `new PublicKey` is pointing to one directory above my root (and .env file).
> > ![image](https://user-images.githubusercontent.com/10168384/132933016-4a5dd3a5-1e0c-4ca5-8963-f661d2dbf5b1.png)
> > Thoughts?
> 
> did you run commands "metaplex upload"?
> the value comes after that: REACT_APP_CANDY_MACHINE_ID
> it should be in .cache/temp

I ran metaplex upload and got REACT_APP_CANDY_MACHINE_CONFIG and REACT_APP_CANDY_MACHINE_ID from the cache but am facing the same issue. 

@studentofcoding go through this https://hackmd.io/@levicook/HJcDneEWF

**Comment by Marxpark** [comment]
I have resolved the above issue by running metaplex create_candy_machine as @raghibislam mentioned. This should be fixed in the readme as this address is not located in the cache file after running metaplex upload. It is also missing in this guide https://hackmd.io/@levicook/HJcDneEWF, i added a brief note in the comments on how to do it. 

Now i'm wondering - what call can i do to alter minting price after creating the candy machine? I created it without the -p parameter and am now trying to set the price of minting, but have a hard time finding a method

**Comment by narodain** [comment]
**$ metaplex create_candy_machine --keypair /Downloads/my-keypair.json**


(node:90256) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_bn' of undefined
    at isPublicKeyData (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:111:16)
    at new PublicKey (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:130:9)
    at /snapshot/js/packages/cli/build/cli.js:423:26
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:90256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:90256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


**How can i solve it ? Thanks**

**Comment by raiseandfall** [comment]
@narodain I've had that issue, this was due to an incorrect structure of my metadata JSON (see my original ticket here: https://github.com/exiled-apes/candy-machine-mint/issues/38)

**Comment by AppAvengers** [comment]
> @narodain I've had that issue, this was due to an incorrect structure of my metadata JSON (see my original ticket here: #38)

Have this json for testing 



{
  "name": "Solflare X NFT",
  "symbol": "Hi",
  "description": "Celebratory Solflare NFT for the Solflare X launch",
  "seller_fee_basis_points": 0,
  "image": "https://www.arweave.net/abcd5678?ext=png",
  "animation_url": "https://www.arweave.net/efgh1234?ext=mp4",
  "external_url": "https://solflare.com",
  "attributes": [
    {
      "trait_type": "web",
      "value": "yes"
    },
    {
      "trait_type": "mobile",
      "value": "yes"
   },
   {
      "trait_type": "extension",
      "value": "yes"
    }
  ],
  "collection": {
     "name": "Solflare X NFT",
     "family": "Solflare"
  },
  "properties": {
    "files": [
      {
        "uri": "https://www.arweave.net/abcd5678?ext=png",
        "type": "image/png"
      },
      {
        "uri": "https://watch.videodelivery.net/9876jkl",
        "type": "unknown",
        "cdn": true
      },
      {
        "uri": "https://www.arweave.net/efgh1234?ext=mp4",
        "type": "video/mp4"
      }
    ],
    "category": "video",
    "creators": [
      {
        "address": "SOLFLR15asd9d21325bsadythp547912501b",
        "share": 100
      }
    ]
  }
}

**Comment by ss5nathan** [comment]
> I have resolved the above issue by running metaplex create_candy_machine as @raghibislam mentioned. This should be fixed in the readme as this address is not located in the cache file after running metaplex upload. It is also missing in this guide https://hackmd.io/@levicook/HJcDneEWF, i added a brief note in the comments on how to do it.
> 
> Now i'm wondering - what call can i do to alter minting price after creating the candy machine? I created it without the -p parameter and am now trying to set the price of minting, but have a hard time finding a method

This also worked for me, extremely confusing as it is noted incorrectly in the readme and not mentioned in that guide either.

**Comment by trust0212** [comment]
Yes. I feel the same as @ss5nathan . I spent 3 days for this. Almost crazy. and have another issue.
`A one_has constraint violated`.
I hope anyone to solve this issue.
Thanks.

**Comment by narodain** [comment]
> @narodain I've had that issue, this was due to an incorrect structure of my metadata JSON (see my original ticket here: #38)

{
  "name": "Solflare X NFT",
  "symbol": "Hi",
  "description": "Celebratory Solflare NFT for the Solflare X launch",
  "seller_fee_basis_points": 0,
  "image": "https://www.arweave.net/abcd5678?ext=png",
  "animation_url": "https://www.arweave.net/efgh1234?ext=mp4",
  "external_url": "https://solflare.com",
  "attributes": [
    {
      "trait_type": "web",
      "value": "yes"
    },
    {
      "trait_type": "mobile",
      "value": "yes"
   },
   {
      "trait_type": "extension",
      "value": "yes"
    }
  ],
  "collection": {
     "name": "Solflare X NFT",
     "family": "Solflare"
  },
  "properties": {
    "files": [
      {
        "uri": "https://www.arweave.net/abcd5678?ext=png",
        "type": "image/png"
      },
      {
        "uri": "https://watch.videodelivery.net/9876jkl",
        "type": "unknown",
        "cdn": true
      },
      {
        "uri": "https://www.arweave.net/efgh1234?ext=mp4",
        "type": "video/mp4"
      }
    ],
    "category": "video",
    "creators": [
      {
        "address": "SOLFLR15asd9d21325bsadythp547912501b",
        "share": 100
      }
    ]
  }
}


This is demo i am using. Thanks.

**Comment by richardj97** [comment]
> Yes. I feel the same as @ss5nathan . I spent 3 days for this. Almost crazy. and have another issue.
> `A one_has constraint violated`.
> I hope anyone to solve this issue.
> Thanks.

Ugh I'm still stuck on this, so annoying -.-

**Comment by ja-leo** [comment]
> "image":

Did you find a way to set the correct "image" URL property? After upload cmd I checked on arweave it didn't auto-change the image placeholder URL with a new value.

**Comment by studentofcoding** [comment]
Hey guys, so what variable to use for .env? 

> REACT_APP_CANDY_MACHINE_CONFIG="get from config"
what config? do you mean this one on .temp?
```
{"program":{"uuid":"...","config":"ktR5U7tC5LAjsy8hVtL66CMqnDP1VfmiAf9J4F3sB5p"},
``` 
> REACT_APP_CANDY_MACHINE_ID="after running create_candy_machine"
As for this do you mean the address that showed on cli after create_candy_machine done?

The way I do right now are I set ..._CONFIG with the address after create_candy_machine & _MACHINE_ID with the one on .temp

Thanks

@raiseandfall 
@mchebib @Marxpark @levicook

**Comment by raiseandfall** [comment]
@studentofcoding I've the opposite and it worked.

**Comment by studentofcoding** [comment]
> @studentofcoding I've the opposite and it worked.

Yupp, the naming are confusing

**Comment by gkiri** [comment]
Facing this issue while minting 
"A has_one constraint was violated:

**Comment by spaceseedtoken** [comment]
> Facing this issue while minting
> "A has_one constraint was violated:

you need to set the treasury address to the "mint authority" value from the .cache file in metaplex/js/packages/cli

**Comment by AcoustiCoder** [comment]
> Something is off when running `npm start`. I get the following error when localhost app runs: Error: Invalid public key input
> 
> Looking further, it seems the `.env` are not being read, because the `new PublicKey` is pointing to one directory above my root (and .env file).
> 
> ![image](https://user-images.githubusercontent.com/10168384/132933016-4a5dd3a5-1e0c-4ca5-8963-f661d2dbf5b1.png)
> 
> Thoughts?

I have same issue. How can i solve?
